version: '3.7'

services:

  # The Back-End Application (Laravel)
  back:
    build:
      context: docker/configurations/back
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor # FIME : Share dependencies with the host ? Comment to enable.
    depends_on:
      - database
    env_file:
      - .env

  # The Front-End Bundler (Webpack)
  front:
    build:
      context: docker/configurations/front
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules # FIME : Share dependencies with the host ? Comment to enable.
    env_file:
      - .env

  # The Reverse Proxy (Nginx)
  proxy:
    image: nginx:stable
    volumes:
      - ./:/var/www/html
      - ./docker/configurations/proxy/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - back

  # The Database (MySQL)
  database:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=portail
      - MYSQL_USER=portail
      - MYSQL_PASSWORD=portail
      - MYSQL_DATABASE=portail
    command: --default-authentication-plugin=mysql_native_password

  # The Mobilizon (Mobilizon)
  mobilizon:
    image: framasoft/mobilizon:2.1.0
    environment:
      - MOBILIZON_INSTANCE_HOST=localhost
      - MOBILIZON_INSTANCE_PORT=4000
      - MOBILIZON_INSTANCE_NAME=Mobilizon_BDE-UTC
      - MOBILIZON_INSTANCE_REGISTRATIONS_OPEN=true
      - MOBILIZON_INSTANCE_EMAIL=picasoft@assos.utc.fr
      - MOBILIZON_REPLY_EMAIL=picasoft@assos.utc.fr
      - MOBILIZON_ADMIN_EMAIL=picasoft@assos.utc.fr
      - MOBILIZON_DATABASE_USERNAME=mobilizon
      - MOBILIZON_DATABASE_PASSWORD=mobilizon
      - MOBILIZON_DATABASE_DBNAME=mobilizon
      - MOBILIZON_DATABASE_HOST=mobilizon-database
    volumes:
      - ./public/uploads:/var/lib/mobilizon/uploads
      # - ${PWD}/config.exs:/etc/mobilizon/config.exs:ro
    ports:
      - "4000:4000"

  mobilizon-database:
    image: postgis/postgis:13-3.1
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mobilizon
      - POSTGRES_PASSWORD=mobilizon
      - POSTGRES_DB=mobilizon

volumes:
  dbdata:
